---
title: "eds212_day2_comp2"
---

## 

```{r}
library(tidyverse)
library(palmerpenguins)
```

plotting functions in ggplot2

```{r}
fx = function(x) {
  3 * x ^ 2 + 4
}
# need what data to use for ggplot. c(x, y) creates a vector with multiple elements (concatenate). aes() - aesthetic mappings
ggplot(data.frame(x = c(1, 100)), aes(x = x)) + geom_function(fun = fx)
```

Partial derivative

```{r}
fxyz = expression(2 * x * y + 3 * (x ^ 2) * (z ^ 3))
# partial derivative
dfdy = D(fxyz, 'y')

dfdy

dfdz = D(fxyz, 'z')

dfdz
```

penguins plot, body mass (x), flipper length (y)

```{r}
# aes is reserved for mapping variables, not constants. in this example, color is determined by species. could also do color = "purple" outside of aes() and all points would be 
ggplot(data = penguins, aes(x = body_mass_g, 
                            y = flipper_length_mm,
                            color = species)) + 
  geom_point() +
  labs(x = "flipper length in mm", 
       y = "mass in g", 
       title = "palmer penguins body dimensions") +
theme_minimal()
```

```{r}
# aes is reserved for mapping variables, not constants. in this example, color is determined by species. could also do color = "purple" outside of aes() and all points would be 
ggplot(data = penguins, aes(x = body_mass_g, 
                            y = flipper_length_mm)) + 
  geom_point(color = "green") +
  labs(x = "flipper length in mm", 
       y = "mass in g", 
       title = "palmer penguins body dimensions") +
theme_minimal()
```
